name: release
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
          registry: https://npm.pkg.github.com/
          scope: '@kuatsu'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn eslint .
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.CICD_PAT }}
          NODE_AUTH_TOKEN: ${{ secrets.CICD_PAT }}
        run: yarn semantic-release
